brico_appli_homepage:
    path:     /
    defaults: { _controller: BricoAppliBundle:Default:index }
    
connexion:
    path:     /connexion
    defaults: { _controller: BricoAppliBundle:Connexion:connexion }

